"""add tenant notification_config

Revision ID: c684e2e3c1cd
Revises: bf442b7f02ee
Create Date: 2026-07-08 08:31:44.451043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c684e2e3c1cd'
down_revision: Union[str, None] = 'bf442b7f02ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing tenant rows with an empty config
    # (opted out of automated delivery) rather than failing the NOT NULL
    # constraint on tenants created before this column existed.
    op.add_column(
        'tenants',
        sa.Column('notification_config', sa.JSON(), nullable=False, server_default='{}'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'notification_config')
    # ### end Alembic commands ###
