"""initial schema

Revision ID: c82538126bc4
Revises: 
Create Date: 2026-07-07 13:16:36.016445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82538126bc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('brand_config', sa.JSON(), nullable=False),
    sa.Column('watchlist_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('briefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brief_type', sa.Enum('daily', 'weekly', 'monthly', name='brieftype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'sent', name='briefstatus'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=1024), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefs_tenant_id'), 'briefs', ['tenant_id'], unique=False)
    op.create_table('story_clusters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('cluster_key', sa.String(length=64), nullable=False),
    sa.Column('primary_article_id', sa.String(), nullable=True),
    sa.Column('pickup_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_clusters_cluster_key'), 'story_clusters', ['cluster_key'], unique=False)
    op.create_index(op.f('ix_story_clusters_tenant_id'), 'story_clusters', ['tenant_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('brand_watch', 'competitor', 'regulator', 'sector', 'custom', name='topickind'), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_tenant_id'), 'topics', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('platform_admin', 'admin', 'analyst', 'client_viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('rss', 'pressreader', 'pdf_upload', 'manual_link', 'social', 'broadcast_transcript', 'google_alerts', name='sourcetype'), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_topic_id'), 'sources', ['topic_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('story_cluster_id', sa.String(), nullable=True),
    sa.Column('publication', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('byline', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('section', sa.String(length=128), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('is_advert', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at_raw', sa.String(length=255), nullable=True),
    sa.Column('published_at_confidence', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'processing', 'classified', 'needs_review', 'rejected', 'error', name='articlestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['story_cluster_id'], ['story_clusters.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=False)
    op.create_index(op.f('ix_articles_story_cluster_id'), 'articles', ['story_cluster_id'], unique=False)
    op.create_index(op.f('ix_articles_tenant_id'), 'articles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_articles_topic_id'), 'articles', ['topic_id'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='classificationstatus'), nullable=False),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('sentiment_overall', sa.Enum('positive', 'neutral', 'negative', name='sentimentlabel'), nullable=True),
    sa.Column('sentiment_by_brand', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('summary_exec', sa.Text(), nullable=True),
    sa.Column('key_quotes', sa.JSON(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('threat_tag', sa.Enum('opportunity', 'monitor', 'risk', name='threattag'), nullable=True),
    sa.Column('threat_rationale', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_article_id'), 'classifications', ['article_id'], unique=True)
    op.create_index(op.f('ix_classifications_tenant_id'), 'classifications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifications_tenant_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_article_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_articles_topic_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_tenant_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_story_cluster_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_sources_topic_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_tenant_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_story_clusters_tenant_id'), table_name='story_clusters')
    op.drop_index(op.f('ix_story_clusters_cluster_key'), table_name='story_clusters')
    op.drop_table('story_clusters')
    op.drop_index(op.f('ix_briefs_tenant_id'), table_name='briefs')
    op.drop_table('briefs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
